language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install: "pip install -r requirements.txt"

script: "coverage run manage.py test --settings=test_site.settings"

# safe list
branches:
  only:
  - master
